# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fn_contribParity <- function(x, Sigma) {
    .Call('_optimist_fn_contribParity', PACKAGE = 'optimist', x, Sigma)
}

gr_contribParity <- function(x, Sigma) {
    .Call('_optimist_gr_contribParity', PACKAGE = 'optimist', x, Sigma)
}

